DROP TABLE IF EXISTS public."receipt_products";
DROP TABLE IF EXISTS public."receipts";
DROP TABLE IF EXISTS public."buys";
DROP TABLE IF EXISTS public."products";
DROP TABLE IF EXISTS public."users";
DROP TABLE IF EXISTS public."categorys";



-------------- Table: public.category
CREATE TABLE IF NOT EXISTS public."categorys"
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text
);
COMMENT ON TABLE public."categorys"
    IS 'Категории товаров';

insert into "categorys" (title)
values
    ('Ракетки'),
    ('Мячи'),
    ('Кроссовки'),
    ('Кеды'),
    ('Куртки'),
    ('Костюмы'),
    ('Рюкзаки'),
    ('Сумки');

----------- Table: public.products
CREATE TABLE IF NOT EXISTS public."products"
(
    id integer NOT NULL primary key generated by default as identity,
    title text,
    brand text,
    price double precision,
    categoryid integer,
    size double precision,
    characteristic text,
    color text,
    foreign key (categoryid) references "categorys" (id)
);
COMMENT ON TABLE public."products"
    IS 'Прайс-лист товаров';

insert into "products" (title,brand,price,categoryid,size,characteristic,color)
values
    ('Ракетка теннисная','Wilson', 25000., 1, 65.0, '300.0 гр.','red'),
    ('Ракетка теннисная','Solinco', 14000., 1, 68.0,'310.0 гр.','yellow'),
    ('Ракетка теннисная','Yonex', 29000., 1, 70.0,'270.0 гр.','black'),
    ('Мяч футбольный','Jogel', 2500., 2, 65.0, '400.0 гр.','white'),
    ('Мяч футбольный','Addidas', 16000., 2, 68.5,'430.0 гр.','silver'),
    ('Мяч футбольный','Nike', 3499., 2, 70.0,'450.0 гр.','green'),
    ('Мяч волейбольный','Mikasa', 5000., 2, 5,'250.0 гр.','yellow-blue'),
    ('Мяч волейбольный','Gala', 3000., 2, 4,'300.0 гр.','white'),
    ('Мяч волейбольный','Torres', 4700., 2, 3,'250.0 гр.','green'),
    ('Кроссовки','Puma',8700., 3, 41,'550.0 гр.','purple'),
    ('Кроссовки','Fila',5700., 3, 45,'650.0 гр.','blue'),
    ('Кроссовки','Reebok',7700., 3, 43,'450.0 гр.','white'),
    ('Кроссовки','Puma',8700., 3, 36,'550.0 гр.','purple'),
    ('Кроссовки','Fila',5700., 3, 38,'650.0 гр.','blue'),
    ('Кроссовки','Reebok',7700., 3, 39,'450.0 гр.','white'),
    ('Кеды','Puma',5700., 4, 36,'250.0 гр.','white'),
    ('Кеды','Fila',2700., 4, 38,'350.0 гр.','white'),
    ('Кеды','Reebok',4700., 4, 39,'350.0 гр.','white'),
    ('Куртка','Adidas',10500., 5, 48,'0','orange'),
    ('Куртка','Puma',15000., 5, 48.5,'0','blue'),
    ('Куртка','Columbia',20700., 5, 50.0,'0.','blue'),
    ('Куртка','Columbia',10700., 5, 54,'0','green'),
    ('Куртка','Adidas',15700., 5, 54.5,'0','pink'),
    ('Куртка','Puma',20700., 5, 56,'0','blue'),
    ('Костюм лыжный','Columbia',15500., 6, 48,'0','orange'),
    ('Костюм лыжный','Colmar',10000., 6, 48.5,'0','blue'),
    ('Костюм лыжный','Phenix',35700., 6, 50.0,'0.','blue'),
    ('Костюм лыжный','Columbia',15700.,6, 48,'0','green'),
    ('Костюм лыжный','Colmar',10700., 6, 50,'0','pink'),
    ('Костюм лыжный','Phenix',35700., 6, 54,'0','blue'),
    ('Рюкзак','Deuter', 12500., 7, 48,'20 л.','green'),
    ('Рюкзак','Nike',11000., 7, 48.5,'80 л.','black'),
    ('Рюкзак','Naturehike',13700., 7, 50.0,'40 л.','pink'),
    ('Сумка','Columbia',2700., 7, 54,'0','orange'),
    ('Сумка','Adidas',5700., 7, 54.5,'0','pink'),
    ('Сумка','Puma',1700., 7, 56,'0','blue');


------------ Table: public.users
CREATE TABLE IF NOT EXISTS public."users"
(
    id integer NOT NULL primary key generated by default as identity,
    firstname text,
    surname text,
    login text,
    passwd text,
    registration date,
    city text,
    country text,
    phone text,
    email text,
    role text DEFAULT 'CLIENT',
    status  text DEFAULT 'ACTIVE'
);
ALTER TABLE users ALTER COLUMN role SET DEFAULT 'CLIENT';
ALTER TABLE users ALTER COLUMN status SET DEFAULT 'ACTIVE';

COMMENT ON TABLE public."users"
    IS 'Клиенты и админы';

-- insert into "users" (firstname,surname,login,passwd,registration,city,country,phone,email)
-- values
--     ('Ирина','Первая', 'i1','$2a$12$FTzWmPMTd3UV4xAWPhDhQOxRrKkwHfFRP0.ITfOCfcQ9Qm3i2WCSa', '2022-10-12','Ульяновск','Россия','890614234566','i1@mail.ru','ADMIN','ACTIVE'),
--     ('Нина','Вторая', 'n2','$2a$12$BrutPcKmeNSgWxPZ5SH8WeY6QIIVQDZAzzXruKPfW', '2022-10-12','Ульяновск','Россия','890614234566','n2@mail.ru','ADMIN','ACTIVE'),
--     ('Иван','Петров', 'iv3','$2a$12$r74vnYszzR1ystFvaCMlHeKwd5NIbCXPY30ejON4CDiQ/UCqM9N3e', '2022-10-12','Ульяновск','Россия','890614234566','iv3@mail.ru','CLIENT','ACTIVE'),
--     ('Иван','Дуров', 'iv4','$2a$12$OKoSVC0aNO/DUVyj5QAbKu2toeGytNVi1Zh/XHKID/5t5uQ2QFJE6', '2022-01-12','Ульяновск','Россия','890614234566','iv4@mail.ru','CLIENT','ACTIVE');

insert into "users" (firstname,surname,login,passwd,registration,city,country,phone,email,role,status)
values
('Ирина','Первая', 'i1','$2a$12$FTzWmPMTd3UV4xAWPhDhQOxRrKkwHfFRP0.ITfOCfcQ9Qm3i2WCSa', '2022-01-12','Ульяновск','Россия','890614234566','i1@mail.ru','SUPERADMIN','ACTIVE'),
('Нина','Вторая', 'n2','$2a$12$BrutPcKmeNSgWxPZ5SH8WeY6QIIVQDZAzzXruKPfW', '2022-02-12','Ульяновск','Россия','890614234566','n2@mail.ru','CLIENT','ACTIVE'),
('Иван','Петров', 'iv3','$2a$12$r74vnYszzR1ystFvaCMlHeKwd5NIbCXPY30ejON4CDiQ/UCqM9N3e', '2022-03-12','Ульяновск','Россия','890614234566','iv3@mail.ru','CLIENT','ACTIVE'),
('Иван','Дуров', 'iv4','$2a$12$OKoSVC0aNO/DUVyj5QAbKu2toeGytNVi1Zh/XHKID/5t5uQ2QFJE6', '2022-04-12','Ульяновск','Россия','890614234566','iv4@mail.ru','CLIENT','ACTIVE');

-- ('Ирина','Первая', 'i1','$2a$12$FTzWmPMTd3UV4xAWPhDhQOxRrKkwHfFRP0.ITfOCfcQ9Qm3i2WCSa', '2022-10-12','Ульяновск','Россия','890614234566','i1@mail.ru'),
-- ('Нина','Вторая', 'n2','$2a$12$BrutPcKmeNSgWxPZ5SH8WeY6QIIVQDZAzzXruKPfW', '2022-10-12','Ульяновск','Россия','890614234566','n2@mail.ru'),
-- ('Иван','Петров', 'iv3','$2a$12$r74vnYszzR1ystFvaCMlHeKwd5NIbCXPY30ejON4CDiQ/UCqM9N3e', '2022-10-12','Ульяновск','Россия','890614234566','iv3@mail.ru'),
-- ('Иван','Дуров', 'iv4','$2a$12$OKoSVC0aNO/DUVyj5QAbKu2toeGytNVi1Zh/XHKID/5t5uQ2QFJE6', '2022-01-12','Ульяновск','Россия','890614234566','iv4@mail.ru');

-------------- Table: public.buy
CREATE TABLE IF NOT EXISTS public."buys"
(
    id int NOT NULL primary key generated by default as identity,
    userid int,
    registration date,
    foreign key (userid) references "users" (id)
);

COMMENT ON TABLE public."buys"
    IS 'Покупки всех Users';

insert into "buys" (id,userid,registration)
values
    (1, 1, '2023-01-21 18:11:05'),
    (2, 1, '2023-01-21 18:11:05'),
    (3, 3, '2023-01-21 18:11:05'),
    (4, 4, '2023-01-21 18:11:05');



-------------- Table: public.receipt_products
CREATE TABLE IF NOT EXISTS public."receipts"
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    buyid integer,
    productid integer,
    count integer,
    foreign key (buyid) references "buys" (id),
    foreign key (productid) references "products" (id)
);
COMMENT ON TABLE public."receipts"
    IS 'Таблица-связь: Количество каждой позиции(покупки) и ее данные';

insert into "receipts" (id,buyid,productid,count)
values
    (1, 1, 1, 1),
    (2, 1, 2, 1),
    (3, 2, 1, 1),
    (4, 3, 1, 1);



